meta_title: "Apero Blind Test"
meta_description: "Apero Blind Test, un jeu à consomer sans modération."
meta_image: "cover.png" # should exist in `app/assets/images/`
meta_url: "www.aperoblindtest.com"
